---
pages:
- posts/how-to-get-a-private-chef-for-255--per-month.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
